name: publish release assets

on:
  push:
    tags:
      - "v*"

jobs:
  freebsd:
    runs-on: macos-latest
    name: FreeBSD
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Build for FreeBSD
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        run: |
          set -ex
          freebsd-version
          pkg install -y gmake zstd
          STATIC=1 ./configure
          gmake
          ./ttyrec -V
          ./ttyrec -V | grep -qF "zstd[static]"
          file ttyrec | grep -qF "statically"
          version=$(./ttyrec -V | head -n1 | cut -d" " -f2 | grep -Eo "[0-9][A-Za-z0-9._-]+")
          mkdir ovh-ttyrec-$version
          strip ttyrec ttyplay ttytime
          install ttyrec ttyplay ttytime ovh-ttyrec-$version
          cp -va docs ovh-ttyrec-$version
          staticname=ovh-ttyrec-${version}_$(uname -m)-freebsd-static-binary.tar.gz
          tar cvzf $staticname ovh-ttyrec-$version
          echo "Static tar.gz archive name is $staticname"
          echo "staticname=$staticname" >> GITHUB_OUTPUT
    - name: Get output name from build in vm
        id: getname
       run: cat GITHUB_OUTPUT >> "$GITHUB_OUTPUT"
    - name: debug
      run: |
         find -type f
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.getname.outputs.staticname }}
        draft: true
